
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const CategoryPage = lazy(() => import("./pages/CategoryPage.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const LessonPage = lazy(() => import("./pages/LessonPage.tsx"));
const Lessons = lazy(() => import("./pages/Lessons.tsx"));
const PlaygroundPage = lazy(() => import("./pages/PlaygroundPage.tsx"));
const PracticePlayground = lazy(() => import("./pages/PracticePlayground.tsx"));
const RoadmapDetail = lazy(() => import("./pages/RoadmapDetail.tsx"));
const Roadmaps = lazy(() => import("./pages/Roadmaps.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/category-page", element: <UserGuard><CategoryPage /></UserGuard>},
	{ path: "/categorypage", element: <UserGuard><CategoryPage /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/lesson-page", element: <UserGuard><LessonPage /></UserGuard>},
	{ path: "/lessonpage", element: <UserGuard><LessonPage /></UserGuard>},
	{ path: "/lessons", element: <UserGuard><Lessons /></UserGuard>},
	{ path: "/playground-page", element: <UserGuard><PlaygroundPage /></UserGuard>},
	{ path: "/playgroundpage", element: <UserGuard><PlaygroundPage /></UserGuard>},
	{ path: "/practice-playground", element: <UserGuard><PracticePlayground /></UserGuard>},
	{ path: "/practiceplayground", element: <UserGuard><PracticePlayground /></UserGuard>},
	{ path: "/roadmap-detail", element: <UserGuard><RoadmapDetail /></UserGuard>},
	{ path: "/roadmapdetail", element: <UserGuard><RoadmapDetail /></UserGuard>},
	{ path: "/roadmaps", element: <UserGuard><Roadmaps /></UserGuard>},

];
